import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft,Download,ReceiptText,ShieldCheck } from 'lucide-react';
import { requireAdminPermission } from '@/lib/auth/admin';
import { checkEInvoiceProviderAction,createInvoiceAdjustmentAction } from '@/lib/invoices/actions';
import { getAdminInvoice,getInvoiceChildren,getInvoiceRefundCandidates } from '@/lib/invoices/queries';
import { INVOICE_DOCUMENT_LABELS,INVOICE_PROVIDER_STATUS_LABELS,INVOICE_STATUS_LABELS,type InvoiceDocumentType } from '@/lib/invoices/types';
import { invoiceAddressLines } from '@/lib/invoices/documents';
import { formatCommercePrice } from '@/lib/commerce/format';
import { ToastActionForm } from '@/components/ui/toast-action-form';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

export const dynamic='force-dynamic';
const date=new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'});

export default async function AdminInvoiceDetailPage({params}:{params:Promise<{invoiceId:string}>}){
  await requireAdminPermission('invoice.view');
  const {invoiceId}=await params;
  const invoice=await getAdminInvoice(invoiceId);
  if(!invoice) notFound();
  const [children,refunds]=invoice.document_type==='invoice'?await Promise.all([getInvoiceChildren(invoice.id),getInvoiceRefundCandidates(invoice.order_id)]):[[],[]];
  const cancellation=children.find((row)=>row.document_type==='cancellation');
  return <div className="grid gap-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/admin/invoices" className="inline-flex items-center gap-2 text-sm font-semibold text-sky-700"><ArrowLeft className="h-4 w-4"/>Faturalara dön</Link><Link href={`/admin/invoices/${invoice.id}/pdf`} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-sky-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-sky-700"><Download className="h-4 w-4"/>PDF İndir</Link></div>
    <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-sky-700">{INVOICE_DOCUMENT_LABELS[invoice.document_type as InvoiceDocumentType]}</p><h1 className="mt-1 text-2xl font-semibold text-gray-950">{invoice.invoice_number}</h1><p className="mt-1 text-sm text-gray-500">{invoice.order?.order_number} · {date.format(new Date(invoice.issued_at))}</p></div><div className="text-right"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${invoice.status==='cancelled'?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{INVOICE_STATUS_LABELS[invoice.status]}</span><p className="mt-3 text-2xl font-semibold text-gray-950">{formatCommercePrice(invoice.total)}</p></div></div>
      <div className="mt-6 grid gap-4 border-t border-gray-100 pt-5 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-gray-500">Müşteri</p><p className="mt-2 font-semibold text-gray-950">{invoice.customer_name}</p><p className="text-sm text-gray-500">{invoice.customer_email}</p>{invoiceAddressLines(invoice.billing_address).map((line)=><p key={line} className="text-sm text-gray-500">{line}</p>)}</div><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-gray-500">Vergi bilgileri</p><p className="mt-2 text-sm text-gray-700">{invoice.customer_tax_office||'Belirtilmedi'}</p><p className="text-sm text-gray-700">{invoice.customer_tax_number||'Belirtilmedi'}</p></div></div>
      <div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-gray-200 text-xs uppercase tracking-[0.12em] text-gray-500"><th className="py-3">Ürün</th><th className="py-3 text-right">Miktar</th><th className="py-3 text-right">KDV</th><th className="py-3 text-right">Tutar</th></tr></thead><tbody>{invoice.items.map((item)=><tr key={item.id} className="border-b border-gray-100"><td className="py-3 font-medium text-gray-900">{item.product_title}<span className="ml-2 text-xs text-gray-400">{item.product_sku}</span></td><td className="py-3 text-right">{item.quantity}</td><td className="py-3 text-right">%{item.tax_rate} · {formatCommercePrice(item.tax_amount)}</td><td className="py-3 text-right font-semibold">{formatCommercePrice(item.line_total)}</td></tr>)}</tbody></table></div>
      <dl className="ml-auto mt-5 grid max-w-sm gap-2 text-sm"><div className="flex justify-between"><dt className="text-gray-500">Ara toplam</dt><dd>{formatCommercePrice(invoice.subtotal)}</dd></div><div className="flex justify-between"><dt className="text-gray-500">İndirim</dt><dd>{formatCommercePrice(invoice.discount_total)}</dd></div><div className="flex justify-between"><dt className="text-gray-500">KDV (dahil)</dt><dd>{formatCommercePrice(invoice.tax_total)}</dd></div><div className="flex justify-between border-t border-gray-200 pt-2 text-base font-semibold"><dt>Genel toplam</dt><dd>{formatCommercePrice(invoice.total)}</dd></div></dl>
    </section>

    <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-sky-700"/><h2 className="text-lg font-semibold text-gray-950">e-Fatura sağlayıcısı</h2></div><p className="mt-2 text-sm text-gray-500">Durum: {INVOICE_PROVIDER_STATUS_LABELS[invoice.provider_status]??invoice.provider_status}. Gerçek sağlayıcı yapılandırılmadan başarılı gönderim üretilmez.</p><ToastActionForm action={checkEInvoiceProviderAction} successMessage="Sağlayıcı hazırlık durumu kaydedildi." errorMessage="Sağlayıcı kontrolü kaydedilemedi." className="mt-4"><input type="hidden" name="invoice_id" value={invoice.id}/><input type="hidden" name="provider_action" value="send"/><Button type="submit" variant="outline">Sağlayıcı Hazırlığını Kontrol Et</Button></ToastActionForm>{invoice.attempts.length?<div className="mt-4 space-y-2">{invoice.attempts.map((attempt)=><p key={attempt.id} className="rounded-xl bg-gray-50 px-3 py-2 text-xs text-gray-600">{date.format(new Date(attempt.created_at))} · {attempt.provider} · {attempt.status} · {attempt.safe_message}</p>)}</div>:null}</section>

    {invoice.document_type==='invoice'?<section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold text-gray-950">Düzeltme belgeleri</h2><div className="mt-4 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-rose-100 bg-rose-50/40 p-4"><h3 className="font-semibold text-rose-900">Fatura iptali</h3>{cancellation?<p className="mt-2 text-sm text-rose-700">{cancellation.invoice_number} oluşturuldu.</p>:invoice.status==='issued'?<ToastActionForm action={createInvoiceAdjustmentAction} successMessage="İptal belgesi oluşturuldu." errorMessage="İptal belgesi oluşturulamadı." confirmation={{title:'Fatura iptal edilsin mi?',description:'Asıl fatura değiştirilmeyecek; tam tutarlı bağlı iptal belgesi oluşturulacak.',confirmLabel:'İptal Belgesi Oluştur',destructive:true}} className="mt-3 grid gap-3"><input type="hidden" name="invoice_id" value={invoice.id}/><input type="hidden" name="document_type" value="cancellation"/><Textarea name="note" rows={2} placeholder="İptal açıklaması" required/><Button type="submit" variant="destructive">Faturayı İptal Et</Button></ToastActionForm>:<p className="mt-2 text-sm text-rose-700">Fatura iptal edildi.</p>}</div><div className="rounded-2xl border border-sky-100 bg-sky-50/40 p-4"><h3 className="font-semibold text-sky-900">İade belgesi</h3>{refunds.length===0?<p className="mt-2 text-sm text-sky-700">Belgelendirilmeyi bekleyen tamamlanmış iade bulunmuyor.</p>:<ToastActionForm action={createInvoiceAdjustmentAction} successMessage="İade belgesi oluşturuldu." errorMessage="İade belgesi oluşturulamadı." confirmation={{title:'İade belgesi oluşturulsun mu?',description:'Yalnız geri ödemesi tamamlanmış iade kalemleri snapshot olarak belgelenecek.',confirmLabel:'İade Belgesi Oluştur'}} className="mt-3 grid gap-3"><input type="hidden" name="invoice_id" value={invoice.id}/><input type="hidden" name="document_type" value="refund"/><div className="grid gap-1.5"><Label>İade talebi</Label><Select name="return_request_id" required>{refunds.map((row)=><option key={row.id} value={row.id}>{row.return_number} · {formatCommercePrice(row.total_refund_amount)}</option>)}</Select></div><Textarea name="note" rows={2} placeholder="İade belgesi açıklaması"/><Button type="submit"><ReceiptText className="h-4 w-4"/>İade Belgesi Oluştur</Button></ToastActionForm>}</div></div>{children.length?<div className="mt-5 flex flex-wrap gap-2">{children.map((child)=><Link key={child.id} href={`/admin/invoices/${child.id}`} className="rounded-xl border border-gray-200 px-3 py-2 text-sm font-semibold text-gray-700 hover:border-sky-300 hover:bg-sky-50">{child.invoice_number}</Link>)}</div>:null}</section>:null}
  </div>;
}
