import { RotateCcw } from 'lucide-react';
import { requireAdminPermission } from '@/lib/auth/admin';
import { getAdminReturns } from '@/lib/returns/queries';
import { RETURN_NEXT_STATUSES, RETURN_STATUS_LABELS, type ReturnStatus } from '@/lib/returns/types';
import { confirmExternalRefundAction, retryReturnRefundAction, transitionReturnRequestAction } from '@/lib/returns/actions';
import { formatCommercePrice } from '@/lib/commerce/format';
import { ToastActionForm } from '@/components/ui/toast-action-form';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

export const dynamic='force-dynamic';
const dateFormatter=new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'});

export default async function AdminReturnsPage(){
  await requireAdminPermission('return.view');
  const returns=await getAdminReturns();
  return <div className="grid gap-5"><section className="rounded-2xl border border-gray-200 bg-white p-6"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-rose-50 text-rose-600"><RotateCcw className="h-5 w-5"/></span><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-rose-600">Faz 24</p><h1 className="text-2xl font-semibold text-gray-950">İade ve geri ödeme</h1></div></div><p className="mt-3 text-sm text-gray-500">Ürün kabulü, stok iadesi, sağlayıcı geri ödemesi ve cari telafi kayıtlarını tek akıştan yönetin.</p></section>
  {returns.length===0?<section className="rounded-2xl border border-gray-200 bg-white p-10 text-center text-gray-500">İade talebi bulunmuyor.</section>:<div className="space-y-4">{returns.map((request)=>{const status=request.status as ReturnStatus;const next=RETURN_NEXT_STATUSES[status]??[];return <article key={request.id} className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold text-gray-950">{request.return_number} · {request.order?.order_number}</p><p className="mt-1 text-sm text-gray-500">{request.customer?.full_name||request.customer?.email||'Müşteri'} · {dateFormatter.format(new Date(request.created_at))}</p><p className="mt-2 text-sm text-gray-700">Neden: {request.reason}</p></div><div className="text-right"><span className="rounded-full bg-rose-50 px-3 py-1 text-xs font-semibold text-rose-700">{RETURN_STATUS_LABELS[status]}</span><p className="mt-2 text-lg font-semibold">{formatCommercePrice(request.total_refund_amount)}</p></div></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-2">{request.items.map((item)=><p key={item.id} className="rounded-xl bg-gray-50 px-3 py-2 text-sm text-gray-700">{item.orderItem?.product_title??'Ürün'} × {item.quantity} · {formatCommercePrice(item.refund_amount)}{item.restocked_at?' · stoğa alındı':''}</p>)}</div>
    {next.length>0?<ToastActionForm action={transitionReturnRequestAction} successMessage="İade durumu güncellendi." errorMessage="İade durumu güncellenemedi." confirmation={{title:'İade durumu değiştirilsin mi?',description:'Stok ve finansal hareketler seçilen aşamaya göre idempotent olarak işlenecek.',confirmLabel:'Durumu Güncelle'}} className="mt-4 grid gap-3 border-t border-gray-100 pt-4 md:grid-cols-[220px_minmax(0,1fr)_auto]"><input type="hidden" name="return_id" value={request.id}/><div className="grid gap-1.5"><Label>Yeni durum</Label><Select name="status">{next.map((value)=><option key={value} value={value}>{RETURN_STATUS_LABELS[value]}</option>)}</Select></div><div className="grid gap-1.5"><Label>Yönetici notu</Label><Textarea name="admin_note" rows={2} defaultValue={request.admin_note}/></div><div className="flex items-end"><Button type="submit">Güncelle</Button></div></ToastActionForm>:null}
    {status==='refund_pending'&&request.refund?<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="font-semibold text-amber-950">Geri ödeme: {request.refund.provider} · {request.refund.status}</p>{request.refund.error_message?<p className="mt-1 text-sm text-amber-800">{request.refund.error_message}</p>:null}<div className="mt-3 grid gap-3 md:grid-cols-2"><ToastActionForm action={retryReturnRefundAction} successMessage="Sağlayıcı geri ödemesi işlendi veya işlem beklemede." errorMessage="Sağlayıcı geri ödemesi başarısız." className="flex items-end"><input type="hidden" name="refund_id" value={request.refund.id}/><Button type="submit" variant="outline">Sağlayıcıyı Yeniden Dene</Button></ToastActionForm><ToastActionForm action={confirmExternalRefundAction} successMessage="Harici geri ödeme teyit edildi." errorMessage="Geri ödeme teyit edilemedi." confirmation={{title:'Harici geri ödeme tamamlandı mı?',description:'Yalnız sağlayıcı panelinde gerçek iade tamamlandıysa onaylayın.',confirmLabel:'Gerçek İadeyi Onayla'}} className="grid gap-2"><input type="hidden" name="refund_id" value={request.refund.id}/><Label>Sağlayıcı iade referansı</Label><div className="flex gap-2"><Input name="provider_reference" required/><Button type="submit">Manuel Teyit</Button></div></ToastActionForm></div></div>:null}
    {request.history.length>0?<details className="mt-4 text-xs text-gray-500"><summary className="cursor-pointer font-semibold">Durum geçmişi</summary><div className="mt-2 space-y-1">{request.history.map((entry)=><p key={entry.id}>{dateFormatter.format(new Date(entry.created_at))} · {RETURN_STATUS_LABELS[entry.to_status as ReturnStatus]??entry.to_status}{entry.note?` · ${entry.note}`:''}</p>)}</div></details>:null}</article>;})}</div>}
  </div>;
}
